CREATE TABLE TANQUE
(
    ID INTEGER NOT NULL,
    DS_TANQUE VARCHAR(50),
    TP_TANQUE INTEGER NOT NULL,
    CONSTRAINT PK_TANQUE PRIMARY KEY(ID)
);

INSERT INTO TANQUE (ID, DS_TANQUE, TP_TANQUE) VALUES (1, 'Tanque 01', 1);
INSERT INTO TANQUE (ID, DS_TANQUE, TP_TANQUE) VALUES (2, 'Tanque 02', 2);

CREATE TABLE BOMBA
(
    ID INTEGER NOT NULL,
    DS_BOMBA VARCHAR(50),
    ID_TANQUE INTEGER NOT NULL,
    CONSTRAINT PK_BOMBA PRIMARY KEY(ID),
    CONSTRAINT FK_BOMBA_TANQUE FOREIGN KEY(ID_TANQUE) REFERENCES TANQUE(ID)
);

INSERT INTO BOMBA (ID, DS_BOMBA, ID_TANQUE) VALUES (1, 'Bomba 01', 1);
INSERT INTO BOMBA (ID, DS_BOMBA, ID_TANQUE) VALUES (2, 'Bomba 02', 1);
INSERT INTO BOMBA (ID, DS_BOMBA, ID_TANQUE) VALUES (3, 'Bomba 03', 2);
INSERT INTO BOMBA (ID, DS_BOMBA, ID_TANQUE) VALUES (4, 'Bomba 04', 2);


CREATE TABLE ABASTECIMENTO
(
    ID INTEGER NOT NULL,
    DT_ABASTECIMENTO TIMESTAMP NOT NULL,
    ID_BOMBA INTEGER NOT NULL,
    NR_LITROS DECIMAL(10,2) NOT NULL,
    VL_TOTAL DECIMAL(10,2) NOT NULL,
    VL_IMPOSTO DECIMAL(10,2) NOT NULL,
    CONSTRAINT PK_ABASTECIMENTO PRIMARY KEY(ID),
    CONSTRAINT FK_ABASTECIMENTO_BOMBA FOREIGN KEY(ID_BOMBA) REFERENCES BOMBA(ID)
);