CREATE TABLE TANQUE
(
    ID INTEGER NOT NULL,
    DS_TANQUE VARCHAR(50),
    TP_TANQUE INTEGER NOT NULL,
    CONSTRAINT PK_TANQUE PRIMARY KEY(ID)
);

CREATE GENERATOR g_TANQUE;

CREATE OR ALTER TRIGGER tg_TANQUE FOR TANQUE
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    NEW.Id = gen_id(g_TANQUE, 1);
END;

INSERT INTO TANQUE (DS_TANQUE, TP_TANQUE) VALUES ('Tanque 01', 1);
INSERT INTO TANQUE (DS_TANQUE, TP_TANQUE) VALUES ('Tanque 02', 2);

CREATE TABLE BOMBA
(
    ID INTEGER NOT NULL,
    DS_BOMBA VARCHAR(50),
    ID_TANQUE INTEGER NOT NULL,
    CONSTRAINT PK_BOMBA PRIMARY KEY(ID),
    CONSTRAINT FK_BOMBA_TANQUE FOREIGN KEY(ID_TANQUE) REFERENCES TANQUE(ID)
);

CREATE GENERATOR g_BOMBA;

CREATE OR ALTER TRIGGER tg_BOMBA FOR BOMBA
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    NEW.Id = gen_id(g_BOMBA, 1);
END;

INSERT INTO BOMBA (DS_BOMBA, ID_TANQUE) VALUES ('Bomba 01', 1);
INSERT INTO BOMBA (DS_BOMBA, ID_TANQUE) VALUES ('Bomba 02', 1);
INSERT INTO BOMBA (DS_BOMBA, ID_TANQUE) VALUES ('Bomba 03', 2);
INSERT INTO BOMBA (DS_BOMBA, ID_TANQUE) VALUES ('Bomba 04', 2);


CREATE TABLE ABASTECIMENTO
(
    ID INTEGER NOT NULL,
    DT_ABASTECIMENTO TIMESTAMP NOT NULL,
    ID_BOMBA INTEGER NOT NULL,
    NR_LITROS DECIMAL(10,2) NOT NULL,
    VL_TOTAL DECIMAL(10,2) NOT NULL,
    VL_IMPOSTO DECIMAL(10,2) NOT NULL,
    CONSTRAINT PK_ABASTECIMENTO PRIMARY KEY(ID),
    CONSTRAINT FK_ABASTECIMENTO_BOMBA FOREIGN KEY(ID_BOMBA) REFERENCES BOMBA(ID)
);

CREATE GENERATOR g_ABASTECIMENTO;

CREATE OR ALTER TRIGGER tg_ABASTECIMENTO FOR ABASTECIMENTO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    NEW.Id = gen_id(g_ABASTECIMENTO, 1);
END;